# Use the latest LTS version of Node.js
FROM node:16-alpine as build
# Set the working directory inside the container
WORKDIR /app 
# Copy package.json and package-lock.json
COPY package*.json ./
# Copy the rest of your application files
COPY . .
# Install dependencies
RUN npm install
RUN npm run build
# Expose the port your app runs on
#EXPOSE 3000
# Define the command to run your app
#CMD ["npm", "start"]
EXPOSE 3000
CMD ["npm", "start"]
# PRODUCCION 
#FROM nginx:alpine
# Copiar configuración personalizada de Nginx
#COPY --from=build /app/build /usr/share/nginx/html
